apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openbao-sandbox

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: openbao
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: sandbox
